events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  server {
    listen 5051;
    root /usr/share/nginx/html;
    index index.html;
    location / {
      try_files $uri $uri/ =404;
    }
    location /tv_snapshot.png {
      # Replace HA_HOST with your Home Assistant server address
      proxy_pass http://HA_HOST:8123/local/tv_snapshot.png;
      proxy_cache_valid 200 10s;
    }
  }
}
